name: Build

on: push

jobs:
  Build:
    runs-on: macos-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 16
      - run: npm run build

  Test:
    runs-on: macos-latest
    needs: Build
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 16

      - run: npm install

      - name: Default Login keychain
        uses: ./
        with:
          github-username: ${{ secrets.GIT_CREDENTIAL_REPOSITORY_USERNAME }}
          github-password: ${{ secrets.GIT_CREDENTIAL_REPOSITORY_PAT }}

      - uses: akiojin/setup-temporary-keychain-github-action@v2.3.2
        id: setup-temporary-keychain
        
      - name: Create temporary keychain
        uses: ./
        with:
          github-username: ${{ secrets.GIT_CREDENTIAL_REPOSITORY_USERNAME }}
          github-password: ${{ secrets.GIT_CREDENTIAL_REPOSITORY_PAT }}
          keychain: ${{ steps.setup-temporary-keychain.outputs.keychain }}
          keychain-password: ${{ steps.setup-temporary-keychain.outputs.keychain-password }}
